### ISSUE TITLE
Install instructions for Mac unclear/not up-to-date

### ISSUE THREAD

**Issue by franzheidl** [camunda/blog.camunda.org#36]
As for installing the custom build of hugo, the RM refers to the Hugo homepage. For Mac, there is only information how to install hugo via homebrew, it is absolutely unclear (at least to me) how to install the custom build downloaded from 

https://app.camunda.com/nexus/content/repositories/public/hugo/

Please update the RM to include actionable installation instructions. 🙏

**Comment by meyerdan** [comment]
You do not need custom hugo build for the blog, AFIK

**Comment by franzheidl** [comment]
Yeah I know, I will only create an `.md` file for now, in the long run it would be cool to have a local preview, and as far as I understand hugo is needed for that?

**Comment by mburke84** [comment]
Try using the darwin build located at https://app.camunda.com/nexus/content/repositories/public/hugo/. 
For installation instructions, check here: https://gohugo.io/getting-started/installing/#macos

Is this helpful?

Cheers

**Comment by sdorokhova** [comment]
Hi @franzheidl , 
I can try to help you, if you want. just approach me.

**Comment by franzheidl** [comment]
Thanks everyone, things are clearing up on my end, so I understand I don’t need the custom build, standard build should work fine. I'll have a go and get back if I don’t succeed.

RM should be updated anyway 🤓

**Comment by franzheidl** [comment]
Ok, seems the blog is **NOT** working with the current standard version of hugo (v0.29), error: 
```
ERROR 2017/09/27 10:23:18 Error while rendering "page": template: theme/post/single.html:1:3: executing "theme/post/single.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:17:8: executing "theme/partials/header.html" at <.RSSlink>: can't evaluate field RSSlink in type *hugolib.PageOutput
ERROR 2017/09/27 10:23:18 Error while rendering "taxonomy": template: theme/_default/list.html:1:3: executing "theme/_default/list.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:17:8: executing "theme/partials/header.html" at <.RSSlink>: can't evaluate field RSSlink in type *hugolib.PageOutput
ERROR 2017/09/27 10:23:18 Error while rendering "home": template: theme/index.html:1:3: executing "theme/index.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:17:8: executing "theme/partials/header.html" at <.RSSlink>: can't evaluate field RSSlink in type *hugolib.PageOutput
ERROR 2017/09/27 10:23:18 Error while rendering "section": template: theme/post/list.html:1:3: executing "theme/post/list.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:17:8: executing "theme/partials/header.html" at <.RSSlink>: can't evaluate field RSSlink in type *hugolib.PageOutput
ERROR 2017/09/27 10:23:18 Error while rendering "taxonomyTerm": template: theme/taxonomy/tag.terms.html:1:3: executing "theme/taxonomy/tag.terms.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:17:8: executing "theme/partials/header.html" at <.RSSlink>: can't evaluate field RSSlink in type *hugolib.PageOutput
```

I could not find any sensible info on how to install an older version og hugo (seems to work fine with v0.16,) on mac / with homebrew / without a degree in computer science, I’ll stop right here and concentrate on writing a blog post…

**Comment by philippfromme** [comment]
On my computer only the Hugo build that is [linked in the README](https://github.com/camunda/blog.camunda.org) of the repo works. Normal Hugo doesn't work with the blog.

**Comment by franzheidl** [comment]
Sigh…

**Comment by franzheidl** [comment]
Ok, the blog theoretically works with the standard version of hugo, althoguh it fails when trying to use the most current version (v0.29). v0.16 works fine, but, at least on the Mac, it is super obscure how to install and older version using homebrew.

I have created an issue to update the blog to use the most current version of hugo: #37 

However, in the meantime it would be good if the RM reflected the current situation, and I shall be happy to update the ReadMe, but since I do not know enough I wanted to double-check first that this is correct:

* blog.camunda.org does work with standard hugo v0.16
* As a workaround, one can get blog.camunda.org to work with v0.29 if https://github.com/camunda/blog.camunda.org/blob/d1907ae1e6c70ff59fbe139c2a7890ccd4f96933/theme-src/layouts/partials/header.html#L17 is commented out locally (**but not committed!**)

I hope this is correct? if yes, I'll update the RM.

**Comment by meyerdan** [comment]
> blog.camunda.org does work with standard hugo v0.16

AFIK this is true
