### ISSUE TITLE
Update to current version of hugo

### ISSUE THREAD

**Issue by franzheidl** [camunda/blog.camunda.org#37]
Currently, to properly work the blog needs hugo v0.16. When trying to run with a current version (v0.29), the build fails due to only one offending in one file:

https://github.com/camunda/blog.camunda.org/blob/d1907ae1e6c70ff59fbe139c2a7890ccd4f96933/theme-src/layouts/partials/header.html#L17

Updating the blog to use the latest version of hugo would massively improve the situation for anyone trying to write a blog post.

**Comment by nikku** [comment]
https://github.com/camunda/blog.camunda.org/pull/41 adds a temporary workaround for this.

**Comment by sdorokhova** [comment]
As the PR is merged and it works fine with standard v0.30.2 for me, I'm closing the issue. Feel free to reopen it, if you feel that some work is still left here.
